<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE config [
        <!ELEMENT config (account,options,setting)>
        <!ELEMENT account (user_name,user_pwd,user_show)>
        <!ELEMENT user_name     (#PCDATA)>
        <!ELEMENT user_pwd      (#PCDATA)>
        <!ELEMENT user_show     (#PCDATA)>
        <!ELEMENT options (remember_pwd,auto_login)>
        <!ELEMENT remember_pwd  (#PCDATA)>
        <!ELEMENT auto_login    (#PCDATA)>
        <!ELEMENT setting (language)>
        <!ELEMENT language      (#PCDATA)>
        ]>
<config>
    <account>
        <user_name>
            default_user_name
        </user_name>
        <user_pwd>
            default_user_pwd
        </user_pwd>
        <user_show>
            true
        </user_show>
    </account>
    <options>
        <remember_pwd>
            false
        </remember_pwd>
        <auto_login>
            false
        </auto_login>
    </options>
    <setting>
        <language>

        </language>
    </setting>
</config>